name: Publish To Sonatype Repository

on:
  push:
    tags:
      - v[0-9]+*
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish to Sonatype
        run: ./gradlew publishAllPublicationsToSonatypeRepository